
CC=gcc
LD=ld
INCLUDES=
PRINT_DEBUG_Y=  -DPRINT_DEBUG_STACK_POINTER  -DPRINT_DEBUG_STACK_PUSH -DPRINT_DEBUG_FOUND_ROLE  -DPRINT_DEBUG_FUNCALL   
PRINT_DEBUG_X=-DPRINT_DEBUG  -DPRINT_DEBUG_OPCODES -DPRINT_DEBUG_INSTRUCTION_COUNT -DPRINT_DEBUG_CODE_POINTER -DPRINT_DEBUG_DISPATCH 
PRINT_DEBUG_1=-DPRINT_DEBUG_DEFUN -DPRINT_DEBUG_GC_1
PRINT_DEBUG_4=-DPRINT_DEBUG_DEFUN -DPRINT_DEBUG_GC  -DPRINT_DEBUG_OPCODES  -DPRINT_DEBUG_CODE_POINTER  -DPRINT_DEBUG_ENSURE -DPRINT_DEBUG_STACK
PRINT_DEBUG_3=-DPRINT_DEBUG_DEFUN -DPRINT_DEBUG_GC -DPRINT_DEBUG_OPTIMIZER -DPRINT_DEBUG_PIC_HITS
PRINT_DEBUG_2=-DPRINT_DEBUG_DEFUN -DPRINT_DEBUG  -DPRINT_DEBUG_OPCODES -DPRINT_DEBUG_INSTRUCTION_COUNT -DPRINT_DEBUG_CODE_POINTER -DPRINT_DEBUG_DISPATCH  -DPRINT_DEBUG_GC_MARKINGS
PRINT_DEBUG=$(PRINT_DEBUG_1)
LIBRARIES_=-lefence -lm -ldl
LIBRARIES=-lm -ldl
#LIBRARIES=
CFLAGS=-std=c99 -Wall -pedantic -pthread $(PRINT_DEBUG)  $(INCLUDES)
#DEBUGFLAGS= -g  -DGC_BUG_CHECK
DEBUGFLAGS= -g 
OBJECTS=

all: vm

backup: superclean
	cd .. && tar  '--exclude=*.git*' -jcvf cslatevm-backup.tar.bz2 cslatevm

plugins:
	make -C src/plugins

vm.debug: vm.c $(OBJECTS)
	gcc $(DEBUGFLAGS) $(CFLAGS) $(LIBRARIES) -o vm.debug vm.c $(OBJECTS)

#fix needs pg on every arg
vm.prof: vm.c $(OBJECTS)
	gcc $(CFLAGS) $(LIBRARIES) -O2 -pg -o vm.prof vm.c $(OBJECTS)


#fix cflags
vm: vm.c $(OBJECTS)
	gcc $(CFLAGS) $(LIBRARIES) -O2 -o vm vm.c $(OBJECTS)


superclean: clean
	rm -f core vm vm.fast vm.prof

pluginsclean:
	make -C src/plugins clean
clean: pluginsclean
	rm -f *.o


.PHONY: clean superclean backup plugins pluginsclean
