(defconst slate-dir (or (getenv "SLATE_ROOT")
			(and load-file-name
			     (concat (file-name-directory load-file-name) ".."))
			default-directory))
(if (not (boundp 'pushnew))
    (defmacro pushnew (item list)
      (`(unless (memq (, item) (, list))
	  (push (, item) (, list))))))
(pushnew (concat slate-dir "/etc") load-path)
(require 'slate-mode)
(defconst slate-cmd (concat slate-dir "/slate"))
(defconst slate-args (list "-q" "-i" (concat slate-dir "/slate.image")))
(cd slate-dir)
(slate-workspace)
(slate)
